development:
  dialect: postgres
  datasource: host=localhost port=5432 user=postgres password=root dbname=timewise sslmode=disable
  dir: migrations
  table: migrations

production:
  dialect: postgres
  datasource: host=localhost port=5432 user=postgres password=root dbname=timewise sslmode=disable
  dir: migrations
  table: migrations